name: Qodana
on:
  push:
  workflow_dispatch:
  pull_request:


jobs:
  qodana:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   pull-requests: write
    #   checks: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request' || github.event.pull_request.merged == true
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ github.event.pull_request.commits }}
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0
      - name: Get one more commit so Qodana we can identify the changes
        if: github.event_name == 'pull_request'
        run: git fetch --deepen=1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run js-test-karma
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          pr-mode: false
          push-fixes: pull-request
          upload-result: true

