name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.6
        with:
          args: -l,jetbrains/qodana-js:2023.2-eap
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
