name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.8
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --ide,QDJS
          primary-cache-key: qd1
          additional-cache-key: dq2
        
